// <auto-generated />
namespace h2hBrainGames.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class IntrochessPiece : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IntrochessPiece));
        
        string IMigrationMetadata.Id
        {
            get { return "201708301957476_Intro chessPiece"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
